# **Working With Columns**

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("/content/raw_data_unmodified.csv", nrows = 4)

In [5]:
data.head()

movie_title  num_critic_for_reviews  \
0                                    Avatar?ÿ                     723   
1  Pirates of the Caribbean: At World's End?ÿ                     302   
2                                   Spectre?ÿ                     602   
3                     The Dark Knight Rises?ÿ                     813   

   duration  DIRECTOR_facebook_likes  actor_3_facebook_likes  \
0     178.0                       10                     855   
1       NaN                      563                    1000   
2     148.0                       20                     161   
3       NaN                    22000                   23000   

   ACTOR_1_facebook_likes      gross  num_voted_users  \
0                    1000  760505847           886204   
1                   40000  309404152           471220   
2                   11000  200074175           275868   
3                   27000  448130642          1144337   

   Cast_Total_facebook_likes  facenumber_in_poster  num_user_for_reviews  \
0                       4834                   NaN                  3054   
1                      48350                   NaN                  1238   
2                      11700                   1.0                   994   
3                     106759                   NaN                  2701   

      budget  title_year  ACTOR_2_facebook_likes  imdb_score  title_year.1  
0  237000000        2009                     936         7.9        2009.0  
1  300000000        2007                    5000         7.1           NaN  
2  245000000        2015                     393         6.8        2015.0  
3  250000000        2012                   23000         8.5           NaN

In [12]:
columns = ["movie_title", "duration"]

data = pd.read_csv("/content/raw_data_unmodified.csv", usecols = columns)

In [13]:
data.head()

movie_title  duration
0                                    Avatar?ÿ     178.0
1  Pirates of the Caribbean: At World's End?ÿ       NaN
2                                   Spectre?ÿ     148.0
3                     The Dark Knight Rises?ÿ       NaN
4                               John Carter?ÿ     132.0

In [6]:
data.columns

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'DIRECTOR_facebook_likes', 'actor_3_facebook_likes',
       'ACTOR_1_facebook_likes', 'gross', 'num_voted_users',
       'Cast_Total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'ACTOR_2_facebook_likes', 'imdb_score', 'title_year.1'],
      dtype='object')

In [7]:
# features of columns: returns a list of all the attributes and methods associated with that object.
dir(data.columns)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_arith_method',
 

In [17]:
data.columns.values    # get columns name as an array

array(['movie_title', 'duration'], dtype=object)

In [18]:
data.columns

Index(['movie_title', 'duration'], dtype='object')

In [23]:
data.columns.view()    # view columns name

Index(['movie_title', 'duration'], dtype='object')

In [21]:
data.columns.tolist()  # get columns name as list

['movie_title', 'duration']

In [26]:
data.columns.to_series()    # convert columns name to a series or dataframe

movie_title    movie_title
duration          duration
dtype: object

In [27]:
data.columns.to_frame()

0
movie_title  movie_title
duration        duration

In [31]:
data.columns.duplicated() #check to see if columns name are duplicated

array([False, False])

In [39]:
dir(data.columns.str)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data',
 '_doc_args',
 '_freeze',
 '_get_series_list',
 '_index',
 '_inferred_dtype',
 '_is_categorical',
 '_is_string',
 '_name',
 '_orig',
 '_parent',
 '_validate',
 '_wrap_result',
 'capitalize',
 'casefold',
 'cat',
 'center',
 'contains',
 'count',
 'decode',
 'encode',
 'endswith',
 'extract',
 'extractall',
 'find',
 'findall',
 'fullmatch',
 'get',
 'get_dummies',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'len',
 'ljust',
 'lower',
 'lstrip',
 'match',
 'normalize',
 'pad',
 '

In [42]:
data.columns.str.lower()

Index(['movie_title', 'duration'], dtype='object')

In [46]:
data.columns.str.capitalize()

Index(['Movie_title', 'Duration'], dtype='object')

In [49]:
data.columns.str.isalpha()

array([False,  True])

In [52]:
data.columns.str.replace("_", "**")

Index(['movie**title', 'duration'], dtype='object')

In [61]:
data.rename(columns = {"duration" : "period"}, inplace = "True")

In [62]:
data.head()

movie_title  period
0                                    Avatar?ÿ   178.0
1  Pirates of the Caribbean: At World's End?ÿ     NaN
2                                   Spectre?ÿ   148.0
3                     The Dark Knight Rises?ÿ     NaN
4                               John Carter?ÿ   132.0

In [65]:
len(data.columns)

2

In [87]:
data.columns.values[1:3] = "DDuration"

In [88]:
data.head()

movie_title  DDuration
0                                    Avatar?ÿ      178.0
1  Pirates of the Caribbean: At World's End?ÿ        NaN
2                                   Spectre?ÿ      148.0
3                     The Dark Knight Rises?ÿ        NaN
4                               John Carter?ÿ      132.0

In [92]:
data.columns.difference(["movie_title"])  #select columns except movie_title

Index(['DDuration'], dtype='object')

In [102]:
data.loc[:, data.columns.isin(["DDuration"])] #select columns name

DDuration
0       178.0
1         NaN
2       148.0
3         NaN
4       132.0
5       156.0
6         NaN
7       141.0
8       141.0
9       153.0
10      183.0
11      169.0
12      106.0
13      151.0

In [104]:
data.loc[:, data.columns.isin(["DDuration"])].columns #select columns name

Index(['DDuration'], dtype='object')

In [103]:
data.loc[:, ~data.columns.isin(["DDuration"])].columns #select column names except one using negation of isin

Index(['movie_title'], dtype='object')

In [110]:
data.columns.str.startswith("movie") #select column names that begin with a word or char

array([ True, False])

In [121]:
data.filter(like = "ration").columns  #select column names that begin with this word or char

Index(['DDuration'], dtype='object')

In [122]:
data.columns.str.endswith("tion") #select column names that end with this word or char

array([False,  True])

In [126]:
data.filter(regex = "ion$").columns  #select column names that end with this word or char

Index(['DDuration'], dtype='object')

In [133]:
data.filter(regex = "mov+", axis = 1).columns  #select column names that end with this word or char

Index(['movie_title'], dtype='object')

In [134]:
data.filter(regex = "mov+", axis = 0).columns  #select column names that end with this word or char

Index(['movie_title', 'DDuration'], dtype='object')

In [139]:
data.columns.values[[0, 1]]

array(['movie_title', 'DDuration'], dtype=object)